spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch
    username: root
    password: root
  batch:
    initialize-schema: always

app:
  datasource:
    url: jdbc:mysql://localhost:3306/migracao_dados
    username: root
    password: root