version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql-migracao-dados
    environment:
      MYSQL_ROOT_PASSWORD: root
    entrypoint: sh -c "
     echo 'CREATE DATABASE IF NOT EXISTS spring_batch; CREATE DATABASE IF NOT EXISTS migracao_dados;' > /docker-entrypoint-initdb.d/init.sql;
     /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    ports:
    - "3306:3306"